23 refactor ble code
ESE-Peasy/NarrateMyWay pull request #34
Opened 2021-03-03 16:21 UTC by C-Begley

# Details

-Updated BLE code to regularly scan and update main screen accordingly

# Screenshots/GIF (if appropriate)
![Screenshot from 2021-03-03 16-17-57](https://user-images.githubusercontent.com/35376967/109836701-5a4fe700-7c3c-11eb-8232-906d3a17af99.png)

# Checklist

## Code
- [ ] I have added some tests
- [ ] I have run the tests locally to ensure they all pass

## Documentation
- [x] I have updated documentation appropriately (GitHub Pages)
- [x] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

## Accessibility
- [ ] Tested Accessibility on **Android**
  - [ ] Any added fields can be read aloud by the screen reader
- [ ] Tested Accessibility on **iOS**
  - [ ] Any added fields can be read aloud by the screen reader

Close # 23

2021-03-03 17:12 UTC, Ashwin-MJ reviewed
Looks good to me, and worked for me on my device too. Only thing is could we move `app/BLE/ble.ts` to `app/src/ble.tsx` please?

2021-03-03 18:49 UTC, Ashwin-MJ submitted a review, later dismissed

2021-03-04 08:51 UTC, miklasr requested changes
Spelling mistake, otherwise very nice

2021-03-04 08:51 UTC, miklasr commented on docs/system/nmw-main-app.md
> +In order to reduce inference caused by temporary loss of a beacon signal, delays have been incorporated into switching of screens. When the app detects a beacon, it switches from the scanning page to
In order to reduce ~inference~ interference ...

2021-03-04 11:54 UTC, Ashwin-MJ approved these changes

2021-03-04 12:06 UTC, miklasr approved these changes

2021-03-04 12:06 UTC, merged