Automate generating standards page
ESE-Peasy/NarrateMyWay pull request #66
Opened 2021-04-16 08:14 UTC by miklasr

# Details

- Makes generating the page for the NMW standard automatic (easier to add new entries)
- Added check in CI to make sure docs version of standard matches app version
  - (Limitation of Pages means this need to be duplicated)
- Additions to the standard

# Checklist

## Documentation
- [ ] I have updated documentation appropriately (GitHub Pages)
- [ ] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

2021-04-16 12:49 UTC, Ashwin-MJ requested changes

2021-04-16 12:49 UTC, Ashwin-MJ commented on app/nmwstandard.json
> +    {"code": "1-6-3", "description": "Public washroom with shower", "icon": ""},
I think we need to have icons defined or the app will not display anything in the area we have allocated for the icon

2021-04-16 12:49 UTC, Ashwin-MJ commented on app/nmwstandard.json
> +    {"code": "4-1-3", "description": "Ticket barrier", "icon": "boom-gate"},
Are you sure this is a valid icon? I ran it on my device and get a question mark. If you're using icons which aren't Ionicons then I think you'll need to update the code accordingly

2021-04-16 12:49 UTC, Ashwin-MJ commented on app/nmwstandard.json
> +    {"code": "4-2-2", "description": "Bus stop", "icon": "bus-stop"},
Same as above

2021-04-20 11:17 UTC, C-Begley commented on .github/workflows/main.yml
> +          npm install
This should be changed to npm install -f

2021-04-20 11:17 UTC, C-Begley commented on .github/workflows/main.yml
> +          npm install
One of Ashwin's libraries needs it too

2021-04-20 11:26 UTC, C-Begley approved these changes, later dismissed

2021-04-20 11:31 UTC, Andrew-Ritchie approved these changes, later dismissed

2021-04-20 11:45 UTC, Ashwin-MJ commented
Have you tested with various beacon names? I can test this in a bit

2021-04-20 11:52 UTC, miklasr commented
> Have you tested with various beacon names? I can test this in a bit

I've tested with the two beacons I have but it's quite tedious to change their names so I haven't tested beyond that. I have, however, tried out the different strings for the icon as the value for the location code set on my beacon. That way I at least know the changes I made to the `Icon` have worked.

2021-04-20 12:16 UTC, Ashwin-MJ reviewed
Tested with a few different beacon names and works well. However, testing with a screen reader results in "Icon of a font awesome 5 shower" being read out. You'll need to change the accessibilityLabel of the `Icon` component. Happy to approve once that's fixed

2021-04-20 13:14 UTC, miklasr commented
> Tested with a few different beacon names and works well. However, testing with a screen reader results in "Icon of a font awesome 5 shower" being read out. You'll need to change the accessibilityLabel of the `Icon` component. Happy to approve once that's fixed

I've changed it to use the current location's description instead of the icon name. That way we won't get any strange output for some icons.

2021-04-20 13:23 UTC, Ashwin-MJ approved these changes

2021-04-20 13:50 UTC, merged