64 permissions
ESE-Peasy/NarrateMyWay pull request #67
Opened 2021-04-16 11:12 UTC by C-Begley

# Details

- Asks user for permissions
- If user denies permission, alert explaining permission is needed, with link to settings or denied
- If the user opens the app twice, denying permissions both times, Android considers permission blocked
- If permission is blocked,only alert appears and no longer asks for permissions 

# Screenshots/GIF (if appropriate)
It can sometimes be useful to add a screenshot or animated GIF to demonstrate new functionality

# Checklist

## Code
- [ ] I have added some tests
- [ ] I have run the tests locally to ensure they all pass

## Documentation
- [ ] I have updated documentation appropriately (GitHub Pages)
- [x] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

## Accessibility
- [x] Tested Accessibility on **Android**
  - [x] Any added fields can be read aloud by the screen reader
- [ ] Tested Accessibility on **iOS**
  - [ ] Any added fields can be read aloud by the screen reader

Closes #

2021-04-16 13:28 UTC, miklasr approved these changes, later dismissed
I've checked different buttons for accepting/declining location permissions. Everything seems to work as expected.

Nice stuff!

2021-04-16 13:31 UTC, Ashwin-MJ requested changes
If I have denied permissions and then have to enable it via settings, when i re-open the app it doesn't seem to actually start scanning for beacons (it doesn't detect anything)

2021-04-16 13:31 UTC, Ashwin-MJ commented on app/App.tsx
> +      console.log(reqs);
Maybe get rid of these and the other logs?

2021-04-16 13:31 UTC, Ashwin-MJ commented on app/App.tsx
> +};
All of this could probably be put in a separate file within `src/` so we only need to import `checkAndGetAllPermissions`?

2021-04-20 08:48 UTC, C-Begley commented
> If I have denied permissions and then have to enable it via settings, when i re-open the app it doesn't seem to actually start scanning for beacons (it doesn't detect anything)

I think if you don't close the app between settings it won't work. I'll try and change that

2021-04-20 15:27 UTC, closed without merging